apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-test.fullname" . }}
  labels:
    {{- include "kube-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "kube-test.selectorLabels" . | nindent 4 }}
